replicaCount: 1

webapp:
    image: hub.k8s.ucar.edu/ncote/utorview-demo:2024-03-04.23.21
    image: hub.k8s.ucar.edu/ncote/utorview-demo:2024-03-04.23.21
  path: /
  tls:
    image: hub.k8s.ucar.edu/ncote/utorview-demo:2024-03-04.23.21
    image: hub.k8s.ucar.edu/ncote/utorview-demo:2024-03-04.23.21
  container: 
    image: hub.k8s.ucar.edu/ncote/utorview-demo:2024-03-04.23.21
    port: 80
    memory: 4G
    cpu: 4