replicaCount: 1

webapp:
  name: utorview-demo
  group: utorview-demo
  path: /
  tls:
    fqdn: utorview-demo.k8s.ucar.edu
    secretName: incommon-cert-utorview-demo
  container: 
    image: hub.k8s.ucar.edu/ncote/utorview-demo-img:v1
    port: 80
    memory: 4G
    cpu: 4